knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(resolve:GOOGLE_ID)%'
            client_secret: '%env(resolve:GOOGLE_SECRET)%'
            redirect_route: google.check
            redirect_params: {}
        facebook:
            # this will be one of the supported types
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: facebook.check
            redirect_params: {}
            graph_api_version: v18.0 #v2.12
        paypal:
            # must be "paypal" - it activates that type!
            type: paypal
            # add and set these environment variables in your .env files
            client_id: '%env(PAYPAL_CLIENT)%'
            client_secret: '%env(PAYPAL_SECRET)%'
            # a route name you'll create
            redirect_route: paypal.check
            redirect_params: {}
            # When true, client uses Paypal Sandbox URLs.
            # is_sandbox: false
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
